# fly.toml app configuration file generated for heimdallr-prod on 2026-08-30T12:06:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heimdallr-prod'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'heimdallr'
  destination = '/var/lib/heimdallr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
