app = "heimdallr"
primary_region = "bos"

[build]
dockerfile = "_fly/Dockerfile"

[build.args]
ENV = "production"

[[vm]]
size = "shared-cpu-2x"

[env]
HEIMDALLR_DEV_MODE_EANBLED = "false"
HEIMDALLR_BOT_DB = "/var/db/heimdallr.db"

[mounts]
source = "litefs"
destination = "/var/db"
