# https://taskfile.dev

version: "3"

env:
  GOPRIVATE: github.com/myrkvi/grem

tasks:
  default:
    desc: Build and run heimdallr
    cmds:
      - task: build
      - task: run
  run:
    desc: Run heimdallr
    preconditions:
      - sh: test -f ./heimdallr{{exeExt}}
        msg: "heimdallr binary not found, please run 'task build' first"
    cmds:
      - ./heimdallr{{exeExt}}
  build:
    desc: Build heimdallr binary
    cmds:
      - task: build-frontend
      - go build -o heimdallr{{exeExt}} .
  build-frontend:
    desc: Build web dashboard and embed into rpcserver
    dir: web-dashboard
    cmds:
      - bun install
      - bun run build
      - rm -rf ../rpcserver/frontend
      - mv dist ../rpcserver/frontend
