# https://taskfile.dev

version: "3"

env:
  GOPRIVATE: github.com/myrkvi/grem
  GOTOOLCHAIN: auto

tasks:
  default:
    desc: Build and run heimdallr
    cmds:
      - task: build
      - task: run
  run:
    desc: Run heimdallr
    preconditions:
      - sh: test -f ./heimdallrbot{{exeExt}}
        msg: "heimdallr binary not found, please run 'task build' first"
    cmds:
      - ./heimdallrbot{{exeExt}}
  build:
    desc: Build heimdallr binary
    cmds:
      - task: build-frontend
      - task: build-backend
  build-backend:
    desc: Build heimdallr backend
    cmds:
      - go generate github.com/NLLCommunity/heimdallr/...
      - >
        go build -a -installsuffix cgo -ldflags "-s -w"
        -tags web -o heimdallrbot{{exeExt}}
        github.com/NLLCommunity/heimdallr
  build-frontend:
    desc: Build web dashboard and embed into rpcserver
    dir: web-dashboard
    cmds:
      - bun install
      - bun run build
      - rm -rf ../heimdallr/rpcserver/frontend
      - cp -rf dist ../heimdallr/rpcserver/frontend
