name: Deploy to test
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: GolangCi-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: GolangCi-Lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: v1.59.1
          args: --timeout=5m
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [lint]
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_TEST }}
